name: Main、Dev 分支 Push 後自動發布專案

on:
    push:
        branches:
        - main # 僅針對合併到 main 分支的 PR
        - dev
        - milestones
        - beta
        - release/*

jobs:
    release:
        runs-on: ubuntu-latest
      
        steps:
        - name: Checkout code
          uses: actions/checkout@v4 
        
        - name: Generate test file
          run: |
            echo "This is a test file." > test.txt        
        
        - name: Setup Node.js
          uses: actions/setup-node@v4
          with:
            node-version: "lts/*"
        
        - name: Cache Node.js modules # <--- 這裡使用快取
          uses: actions/cache@v4
          with:
            path: ~/.npm # 快取 npm 的快取目錄，或者直接快取 node_modules: path: node_modules
            key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }} # 快取鍵，基於 OS 和 package-lock.json 的哈希值
            restore-keys: |
              ${{ runner.os }}-node-
        
        - name: Install dependencies # <--- 安裝依賴 (如果快取命中則跳過或很快)
          run: npm ci 

        - name: Release
          run: |
            npx semantic-release
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN  }}
