name: Main、Dev 分支 Push 後自動發布專案

on:
    push:
        branches:
        - main # 僅針對合併到 main 分支的 PR
        - dev
        - milestones

jobs:
    release:
        runs-on: ubuntu-latest
      
        steps:
        - name: Checkout code
          uses: actions/checkout@v4 
        
        - name: Generate test file
          run: |
            echo "This is a test file." > test.txt        
        
        - name: Setup Node.js
          uses: actions/setup-node@v4
          with:
            node-version: "lts/*"

        - name: Release
          run: |
            npx semantic-release
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN  }}
